export const types = {
"Budget":"../assets/icons/types/Basic.jpg",
"Create-A-Monster":"../assets/icons/types/Create-A-Monster.jpg",
"Doll": "../assets/icons/types/Doll.jpg",
"Inner Monster": "../assets/icons/types/Inner.jpg",
"Multipack": "../assets/icons/types/Multipack.jpg",
"Playset": "../assets/icons/types/Playsets.jpg",
};

export const icons = {
  "Frankie Stein":"../assets/icons/characters/Frankie_Skullette.webp",
  "Draculaura":"../assets/icons/characters/Draculaura_Skullette.webp",
  "Clawdeen Wolf":"../assets/icons/characters/Clawdeen_Skullette.webp",
  "Cleo de Nile":"../assets/icons/characters/Cleo_Skullette.webp",
  "Lagoona Blue":"../assets/icons/characters/Lagoona_Skullette.webp",
  "Ghoulia Yelps":"../assets/icons/characters/Ghoulia_Skullette.webp",
  "Ari Hauntington":"../assets/icons/characters/Ari_Skullette.webp",
  "Abbey Bominable":"../assets/icons/characters/Abbey_Skullette.webp",
  "Operetta":"../assets/icons/characters/Operetta_Skullette.webp",
  "Rochelle Goyle":"../assets/icons/characters/Rochelle_Skullette.webp",
  "Robecca Steam":"../assets/icons/characters/Robecca_Skullette.webp",
  "Venus McFlytrap":"../assets/icons/characters/Venus_skullette.webp",
  "Spectra Vondergeist":"../assets/icons/characters/Spectra_Skullette.webp",
  "Toralei Stripe":"../assets/icons/characters/Toralei_Skullette.webp",
  "Meowlody":"../assets/icons/characters/Meowlody_Skullette.webp",
  "Purrsephone":"../assets/icons/characters/Purrsephone_Skullette.webp",
  "Nefera de Nile":"../assets/icons/characters/Nefera_Skullette.PNG",
  "Deuce Gorgon":"../assets/icons/characters/Deuce_Skullette.webp",
  "Jackson Jekyll":"../assets/icons/characters/Jackson_Skullette.webp",
  "Holt Hyde":"../assets/icons/characters/Holt_Skullette.webp",
  "Clawd Wolf":"../assets/icons/characters/Clawd_Skullette.webp",
  "Gillington Gil Webber":"../assets/icons/characters/Gil_Skullette.webp",
  "Heath Burns":"../assets/icons/characters/Heath_Skullette.webp",
  "Sloman Slo Mo Mortavitch":"../assets/icons/characters/SloMo_Skullette.webp",
  "Invisi Billy":"../assets/icons/characters/Invisi_Skullette.webp",
  "Howleen Wolf":"../assets/icons/characters/Howleen_Skullette.webp",
  "Gigi Grant":"../assets/icons/characters/Gigi_Skullette.webp",
  "Twyla Boogeyman":"../assets/icons/characters/Twyla_skullette.webp",
  "Catty Noir":"../assets/icons/characters/CattyNoir_Skullette.webp",
  "Skelita Calaveras":"../assets/icons/characters/Skelita_Skullette.webp",
  "Jinafire Long":"../assets/icons/characters/Jinafire_Skullette.webp",
  "Catrine DeMew":"../assets/icons/characters/Catrine_skullette.webp",
  "Garrott du Roque":"../assets/icons/characters/Garrot_Skullette.webp",
  "Scarah Screams":"../assets/icons/characters/Scarah_Skullette.webp",
  "Hoodude Voodoo":"../assets/icons/characters/Hoodude_Skullette.webp",
  "Iris Clops":"../assets/icons/characters/Iris_Skullette.webp",
  "Manny Taur":"../assets/icons/characters/Manny_Skullette.webp",
  "Headless Headmistress Bloodgood":"../assets/icons/characters/Bloodgood_Skullette.webp",
  "Wydowna Spider":"../assets/icons/characters/Wydowna_Skullette.webp",
  "Jane Boolittle":"../assets/icons/characters/Jane_Skullette.webp",
  "Gilda Goldstag":"../assets/icons/characters/Gilda_Skullette.webp",
  "Honey Swamp":"../assets/icons/characters/Honey_Skullette.webp",
  "Clawdia Wolf":"../assets/icons/characters/Clawdia_SKullette.webp",
  "Elissabat":"../assets/icons/characters/Elissabat_Skullette.webp",
  "Viperine Gorgon":"../assets/icons/characters/Viperine_Skullette.webp",
  "Avea Trotter":"../assets/icons/characters/Avea_Skullette.PNG",
  "Bonita Femur":"../assets/icons/characters/Bonita_Skullette.webp",
  "Neighthan Rot":"../assets/icons/characters/Neighthans_Skullette.webp",
  "Sirena Von Boo":"../assets/icons/characters/Sirena_skullette.webp",
  "River Styxx":"../assets/icons/characters/River_Skullette.PNG",
  "Kiyomi Haunterly":"../assets/icons/characters/Kiyomi_Skullette.webp",
  "Porter Geiss":"../assets/icons/characters/Porter_Skullette.webp",
  "Vandala Doubloons":"../assets/icons/characters/Vandala_Skullette.PNG",
  "Astranova":"../assets/icons/characters/Astranova_Skullette.PNG.webp",
  "Luna Mothews":"../assets/icons/characters/Luna_Skullette.PNG",
  "Elle Eedee":"../assets/icons/characters/Elle_Skullette.PNG",
  "Mouscedes King":"../assets/icons/characters/Mouscedes_Skullette.PNG",
  "Finnegan Wake":"../assets/icons/characters/Finnegan_Skullette.PNG.webp",
  "Amanita Nightshade":"../assets/icons/characters/Amanita_Skullette.PNG",
  "Gooliope Jellington":"../assets/icons/characters/Gooliope_Skullette.webp",
  "Marisol Coxi":"../assets/icons/characters/Marisol_Skullette.webp",
  "Lorna McNessie":"../assets/icons/characters/Lorna_Skullette.webp",
  "Batsy Claro":"../assets/icons/characters/Batsy_Skullette.webp",
  "Kjersti Trollson":"../assets/icons/characters/Kjersti_SKullette.webp",
  "Isi Dawndancer":"../assets/icons/characters/Isi_Skullette.PNG",
  "C.A. Cupid":"../assets/icons/characters/C.A._Cupid_Skullette.PNG.webp",
  "Kieran Valentine":"../assets/icons/characters/Kieran_Skullette.PNG.webp",
  "Djinni Whisp Grant":"../assets/icons/characters/Whisp_Skullette.PNG.webp",
  "Casta Fierce":"../assets/icons/characters/CastaFierce_Skullette.webp",
  "Peri & Pearl Serpentine": "../assets/icons/characters/Serpentine_Skullette.png",
  "Kala Mer'ri": "../assets/icons/characters/Kala_Skullette.png",
  "Beetlejuice":"../assets/icons/characters/Beetlejuice_Skullette.webp",
  "Beetrice":"../assets/icons/characters/Beetrice_Skullette_2.webp",
  "Dracula":"../assets/icons/characters/Dracula_Skullette.webp",
  "Grady Twins": "../assets/icons/characters/Grady_Twins_Skullette.webp",
  "Moanica D'Kay":"../assets/icons/characters/Moanica_Skullette.PNG.webp",
  "Pennywise": "../assets/icons/characters/Pennywise_Skullette.webp",
  "Porter Paintergeist Geiss": "../assets/icons/characters/Porter_Skullette.webp",
  "Posea Reef":"../assets/icons/characters/Posea_Skullette.webp"
};


export const iconsLogo = {
  "Signature":"../assets/icons/series/Signature.webp",
  "Dawn of the Dance":"../assets/icons/series/Dawn_of_the_Dance.webp",
  "Gloom Beach":"../assets/icons/series/Gloom_Beach.webp",
  "Sweet 1600":"../assets/icons/series/Sweet_1600.webp",
  "Dead Tired":"https://static.wikia.nocookie.net/monsterhigh/images/2/2b/Dead_Tired_Icon.jpg",
  "Skull Shores":"https://static.wikia.nocookie.net/monsterhigh/images/4/45/SkullShoresLogo.png",
  "Dot Dead Gorgeous":"https://static.wikia.nocookie.net/monsterhigh/images/e/e2/Assortment_logo_-_Dot_Dead_Gorgeous.png",
  "Ghouls Rule":"https://static.wikia.nocookie.net/monsterhigh/images/1/16/Assortment_logo_-_Ghouls_Rule.png",
  "I Love Fashion":"https://static.wikia.nocookie.net/monsterhigh/images/7/73/I_Heart_Fashion_Icon.png",
  "Scaris: City of Frights":"https://static.wikia.nocookie.net/monsterhigh/images/3/3e/Assortment_logo_-_Scaris_City_of_Frights.jpg",
  "Ghoul’s Alive!":"https://static.wikia.nocookie.net/monsterhigh/images/7/7e/Assortment_logo_-_Ghoul%27s_Alive.png",
  "Skultimate Roller Maze":"https://static.wikia.nocookie.net/monsterhigh/images/a/ae/Assortment_logo_-_Skultimate_Roller_Maze.png",
  "Dance Class":"https://static.wikia.nocookie.net/monsterhigh/images/6/63/Assortment_logo_-_Dance_Class.jpg",
  "Picture Day":"https://static.wikia.nocookie.net/monsterhigh/images/e/e5/Assortment_logo_-_Picture_Day.png",
  "Power Ghouls":"https://static.wikia.nocookie.net/monsterhigh/images/f/f3/Assortment_logo_-_Power_Ghouls.png",
  "13 Wishes":"https://static.wikia.nocookie.net/monsterhigh/images/8/8f/Assortment_logo_-_13_Wishes.jpg",
  "Ghoul’s Night Out":"https://static.wikia.nocookie.net/monsterhigh/images/0/04/Assortment_logo_-_Ghouls_Night_Out.png",
  "Art Class":"https://static.wikia.nocookie.net/monsterhigh/images/8/87/Assortment_logo_-_Art_Class.png",
  "Music Festival":"https://static.wikia.nocookie.net/monsterhigh/images/b/b2/Assortment_logo_-_Music_Festival.png",
  "Monster Exchange":"https://static.wikia.nocookie.net/monsterhigh/images/a/a1/Monster_Exchange_Icon.png",
  "Zombie Shake":"https://static.wikia.nocookie.net/monsterhigh/images/a/af/Zombie_Shake_Icon.png",
  "Freaky Fusion":"https://static.wikia.nocookie.net/monsterhigh/images/6/61/Freaky_Fusion_Icon.png",
  "Haunted":"https://static.wikia.nocookie.net/monsterhigh/images/3/34/Haunted_Icon.png",
  "Gloom and Bloom":"https://static.wikia.nocookie.net/monsterhigh/images/e/e2/Gloom_and_Bloom_Icon.png",
  "Coffin Bean":"https://static.wikia.nocookie.net/monsterhigh/images/1/1c/Coffin_Bean_Icon.png",
  "Creepateria":"https://static.wikia.nocookie.net/monsterhigh/images/d/d4/Creepateria_Icon.png",
  "Freaky Field Trip":"https://static.wikia.nocookie.net/monsterhigh/images/1/10/Freaky_Field_Trip_Icon.png",
  "Geek Shriek":"https://static.wikia.nocookie.net/monsterhigh/images/7/7b/Geek_Shriek_Icon.png",
  "Boo York, Boo York":"https://static.wikia.nocookie.net/monsterhigh/images/5/52/Boo_York%2C_Boo_York_Icon.png",
  "Freak du Chic":"https://static.wikia.nocookie.net/monsterhigh/images/5/58/Freak_Du_Chic_Noir_Icon.png",
  "Great Scarrier Reef":"https://static.wikia.nocookie.net/monsterhigh/images/4/4e/Yayomg-great-scarrier-reef-333x166_%282%29.png",
  "Scarnival":"https://static.wikia.nocookie.net/monsterhigh/images/b/b6/Clawd_wolf_scarnival_booth_doll_in_box.png",
  "Gore-geous Accessories":"https://static.wikia.nocookie.net/monsterhigh/images/c/c3/Gore-geous_Accessories_Icon.png",
  "Fangtastic Fitnes":"https://static.wikia.nocookie.net/monsterhigh/images/a/a8/Fangtastic_Fitness_Icon.png",
  "Ghoul Fair":"https://static.wikia.nocookie.net/monsterhigh/images/4/40/Ghoul_Fair_Icon.png",
  "Frightfully Tall Ghouls":"https://static.wikia.nocookie.net/monsterhigh/images/3/3b/Frightfully_Tall_Ghouls_Icon.png",
  "Skullector":"https://static.wikia.nocookie.net/monsterhigh/images/7/79/Skullector.png"
}


