export const types = {
"Budget":"../assets/icons/types/Basic.jpg",
"Create-A-Monster":"../assets/icons/types/Create-A-Monster.jpg",
"Doll": "../assets/icons/types/Doll.jpg",
"Inner Monster": "../assets/icons/types/Inner.jpg",
"Multipack": "../assets/icons/types/Multipack.jpg",
"Playset": "../assets/icons/types/Playsets.jpg",
};

export const characters = {
  "Frankie Stein":"../assets/icons/characters/Frankie_Skullette.webp",
  "Draculaura":"../assets/icons/characters/Draculaura_Skullette.webp",
  "Clawdeen Wolf":"../assets/icons/characters/Clawdeen_Skullette.webp",
  "Cleo de Nile":"../assets/icons/characters/Cleo_Skullette.webp",
  "Lagoona Blue":"../assets/icons/characters/Lagoona_Skullette.webp",
  "Ghoulia Yelps":"../assets/icons/characters/Ghoulia_Skullette.webp",
  "Ari Hauntington":"../assets/icons/characters/Ari_Skullette.webp",
  "Abbey Bominable":"../assets/icons/characters/Abbey_Skullette.webp",
  "Operetta":"../assets/icons/characters/Operetta_Skullette.webp",
  "Rochelle Goyle":"../assets/icons/characters/Rochelle_Skullette.webp",
  "Robecca Steam":"../assets/icons/characters/Robecca_Skullette.webp",
  "Venus McFlytrap":"../assets/icons/characters/Venus_skullette.webp",
  "Spectra Vondergeist":"../assets/icons/characters/Spectra_Skullette.webp",
  "Toralei Stripe":"../assets/icons/characters/Toralei_Skullette.webp",
  "Meowlody":"../assets/icons/characters/Meowlody_Skullette.webp",
  "Purrsephone":"../assets/icons/characters/Purrsephone_Skullette.webp",
  "Nefera de Nile":"../assets/icons/characters/Nefera_Skullette.PNG",
  "Deuce Gorgon":"../assets/icons/characters/Deuce_Skullette.webp",
  "Jackson Jekyll":"../assets/icons/characters/Jackson_Skullette.webp",
  "Holt Hyde":"../assets/icons/characters/Holt_Skullette.webp",
  "Clawd Wolf":"../assets/icons/characters/Clawd_Skullette.webp",
  "Gillington Gil Webber":"../assets/icons/characters/Gil_Skullette.webp",
  "Heath Burns":"../assets/icons/characters/Heath_Skullette.webp",
  "Sloman Slo Mo Mortavitch":"../assets/icons/characters/SloMo_Skullette.webp",
  "Invisi Billy":"../assets/icons/characters/Invisi_Skullette.webp",
  "Howleen Wolf":"../assets/icons/characters/Howleen_Skullette.webp",
  "Gigi Grant":"../assets/icons/characters/Gigi_Skullette.webp",
  "Twyla Boogeyman":"../assets/icons/characters/Twyla_skullette.webp",
  "Catty Noir":"../assets/icons/characters/CattyNoir_Skullette.webp",
  "Skelita Calaveras":"../assets/icons/characters/Skelita_Skullette.webp",
  "Jinafire Long":"../assets/icons/characters/Jinafire_Skullette.webp",
  "Catrine DeMew":"../assets/icons/characters/Catrine_skullette.webp",
  "Garrott du Roque":"../assets/icons/characters/Garrot_Skullette.webp",
  "Scarah Screams":"../assets/icons/characters/Scarah_Skullette.webp",
  "Hoodude Voodoo":"../assets/icons/characters/Hoodude_Skullette.webp",
  "Iris Clops":"../assets/icons/characters/Iris_Skullette.webp",
  "Manny Taur":"../assets/icons/characters/Manny_Skullette.webp",
  "Headless Headmistress Bloodgood":"../assets/icons/characters/Bloodgood_Skullette.webp",
  "Wydowna Spider":"../assets/icons/characters/Wydowna_Skullette.webp",
  "Jane Boolittle":"../assets/icons/characters/Jane_Skullette.webp",
  "Gilda Goldstag":"../assets/icons/characters/Gilda_Skullette.webp",
  "Honey Swamp":"../assets/icons/characters/Honey_Skullette.webp",
  "Clawdia Wolf":"../assets/icons/characters/Clawdia_SKullette.webp",
  "Elissabat":"../assets/icons/characters/Elissabat_Skullette.webp",
  "Viperine Gorgon":"../assets/icons/characters/Viperine_Skullette.webp",
  "Avea Trotter":"../assets/icons/characters/Avea_Skullette.PNG",
  "Bonita Femur":"../assets/icons/characters/Bonita_Skullette.webp",
  "Neighthan Rot":"../assets/icons/characters/Neighthans_Skullette.webp",
  "Sirena Von Boo":"../assets/icons/characters/Sirena_skullette.webp",
  "River Styxx":"../assets/icons/characters/River_Skullette.PNG",
  "Kiyomi Haunterly":"../assets/icons/characters/Kiyomi_Skullette.webp",
  "Porter Geiss":"../assets/icons/characters/Porter_Skullette.webp",
  "Vandala Doubloons":"../assets/icons/characters/Vandala_Skullette.PNG",
  "Astranova":"../assets/icons/characters/Astranova_Skullette.PNG.webp",
  "Luna Mothews":"../assets/icons/characters/Luna_Skullette.PNG",
  "Elle Eedee":"../assets/icons/characters/Elle_Skullette.PNG",
  "Mouscedes King":"../assets/icons/characters/Mouscedes_Skullette.PNG",
  "Finnegan Wake":"../assets/icons/characters/Finnegan_Skullette.PNG.webp",
  "Amanita Nightshade":"../assets/icons/characters/Amanita_Skullette.PNG",
  "Gooliope Jellington":"../assets/icons/characters/Gooliope_Skullette.webp",
  "Marisol Coxi":"../assets/icons/characters/Marisol_Skullette.webp",
  "Lorna McNessie":"../assets/icons/characters/Lorna_Skullette.webp",
  "Batsy Claro":"../assets/icons/characters/Batsy_Skullette.webp",
  "Kjersti Trollson":"../assets/icons/characters/Kjersti_SKullette.webp",
  "Isi Dawndancer":"../assets/icons/characters/Isi_Skullette.PNG",
  "C.A. Cupid":"../assets/icons/characters/C.A._Cupid_Skullette.PNG.webp",
  "Kieran Valentine":"../assets/icons/characters/Kieran_Skullette.PNG.webp",
  "Djinni Whisp Grant":"../assets/icons/characters/Whisp_Skullette.PNG.webp",
  "Casta Fierce":"../assets/icons/characters/CastaFierce_Skullette.webp",
  "Peri & Pearl Serpentine": "../assets/icons/characters/Serpentine_Skullette.png",
  "Kala Mer'ri": "../assets/icons/characters/Kala_Skullette.png",
  "Beetlejuice":"../assets/icons/characters/Beetlejuice_Skullette.webp",
  "Beetrice":"../assets/icons/characters/Beetrice_Skullette_2.webp",
  "Count Dracula":"../assets/icons/characters/Dracula_Skullette.webp",
  "Grady Twins": "../assets/icons/characters/Grady_Twins_Skullette.webp",
  "Moanica D'Kay":"../assets/icons/characters/Moanica_Skullette.PNG.webp",
  "Pennywise": "../assets/icons/characters/Pennywise_Skullette.webp",
  "Porter Paintergeist Geiss": "../assets/icons/characters/Porter_Skullette.webp",
  "Posea Reef":"../assets/icons/characters/Posea_Skullette.webp"
};

export const years = {
"2010":"../assets/icons/years/2010.webp",
"2011":"../assets/icons/years/2011.webp",
"2012":"../assets/icons/years/2012.webp",
"2013":"../assets/icons/years/2013.webp",
"2014":"../assets/icons/years/2014.webp",
"2015":"../assets/icons/years/2015.webp",
"2016":"../assets/icons/years/2016.webp",
"2017":"../assets/icons/years/2017.webp",
"2018":"../assets/icons/years/2017.webp",
"2020":"../assets/icons/years/2020.webp",
"2021":"../assets/icons/years/2020.webp",
"2022":"../assets/icons/years/2017.webp",
};

export const genders = {
  "Ghoul":"../assets/icons/gender/Ghoul.jpg",
  "Manster":"../assets/icons/gender/Manster.jpg"
}


export const series = {
  "Signature":"../assets/icons/series/Signature.webp",
  "Dawn of the Dance":"../assets/icons/series/Dawn_of_the_Dance.webp",
  "Gloom Beach":"../assets/icons/series/Gloom_Beach.webp",
  "Sweet 1600":"../assets/icons/series/Sweet_1600.webp",
  "Dead Tired":"../assets/icons/series/Dead_Tired.webp",
  "Skull Shores":"../assets/icons/series/SkullShores.webp",
  "Dot Dead Gorgeous":"../assets/icons/series/Dot_Dead_Gorgeous.webp",
  "Ghouls Rule":"../assets/icons/series/Ghouls_Rule.webp",
  "I Love Fashion":"../assets/icons/series/I_Heart_Fashion_Icon.webp",
  "Scaris: City of Frights":"../assets/icons/series/Scaris_City_of_Frights.webp",
  "Ghoul’s Alive!":"../assets/icons/series/Ghoul_Alive.webp",
  "Skultimate Roller Maze":"../assets/icons/series/Skultimate_Roller_Maze.webp",
  "Dance Class":"../assets/icons/series/Dance_Class.webp",
  "Picture Day":"../assets/icons/series/Picture_Day.webp",
  "Power Ghouls":"../assets/icons/series/Power_Ghouls.webp",
  "13 Wishes":"../assets/icons/series/13_Wishes.webp",
  "Ghoul’s Night Out":"../assets/icons/series/Ghouls_Night_Out.webp",
  "Art Class":"../assets/icons/series/Art_Class.webp",
  "Music Festival":"../assets/icons/series/Music_Festival.webp",
  "Monster Exchange":"../assets/icons/series/Monster_Exchange_Icon.webp",
  "Zombie Shake":"../assets/icons/series/Zombie_Shake_Icon.webp",
  "Freaky Fusion":"../assets/icons/series/Freaky_Fusion_Icon.webp",
  "Haunted":"../assets/icons/series/Haunted_Icon.webp",
  "Gloom and Bloom":"../assets/icons/series/Gloom_and_Bloom_Icon.webp",
  "Coffin Bean":"../assets/icons/series/Coffin_Bean_Icon.webp",
  "Creepateria":"../assets/icons/series/Creepateria_Icon.webp",
  "Freaky Field Trip":"../assets/icons/series/Freaky_Field_Trip_Icon.webp",
  "Geek Shriek":"../assets/icons/series/Geek_Shriek_Icon.webp",
  "Boo York, Boo York":"../assets/icons/series/Boo_York.webp",
  "Freak du Chic":"../assets/icons/series/Freak_Du_Chic_Noir.webp",
  "Great Scarrier Reef":"../assets/icons/series/Great-scarrier-reef.webp",
  "Scarnival":"../assets/icons/series/Clawd_wolf_scarnival_booth_doll_in_box.webp",
  "Gore-geous Accessories":"../assets/icons/series/Gore-geous_Accessories_Icon.webp",
  "Fangtastic Fitnes":"../assets/icons/series/Fangtastic_Fitness.webp",
  "Ghoul Fair":"../assets/icons/series/Ghoul_Fair.webp",
  "Frightfully Tall Ghouls":"../assets/icons/series/Frightfully_Tall_Ghouls.webp",
  "Skullector":"../assets/icons/series/Skullector.webp"
}

export const exclusives = {
  "Comic Con":"../assets/icons/exclusives/Comic_Con.webp",
  "Toys”R”Us":"../assets/icons/exclusives/Toys__R__Us.svg.png",
  "Target": "../assets/icons/exclusives/Target.svg.png",
  "Walmart":'../assets/icons/exclusives/Walmart.png',
  "Kohls": "../assets/icons/exclusives/Kohls.png",
  "Costco":"../assets/icons/exclusives/Costco.jpg",
  "JCPenney":"../assets/icons/exclusives/JCPenney.jpg",
  "KMart":"../assets/icons/exclusives/Kmart.jpg",
  "Justice":"../assets/icons/exclusives/Justice.png",
  "Amazon":"../assets/icons/exclusives/Amazon.svg.png",
  "Mattel Shop":"../assets/icons/exclusives/Mattel.png"
};


