export const icons = {
  "Frankie Stein":"https://static.wikia.nocookie.net/monsterhigh/images/8/84/Frankie_Skullette.png",
  "Draculaura":"https://static.wikia.nocookie.net/monsterhigh/images/9/98/Draculaura_Skullette.png",
  "Clawdeen Wolf":"https://static.wikia.nocookie.net/monsterhigh/images/6/65/Clawdeen_Skullette.png",
  "Cleo de Nile":"https://static.wikia.nocookie.net/monsterhigh/images/4/46/Cleo_Skullette.png",
  "Lagoona Blue":"https://static.wikia.nocookie.net/monsterhigh/images/f/f0/Lagoona_Skullette.png",
  "Ghoulia Yelps":"https://static.wikia.nocookie.net/monsterhigh/images/3/30/Ghoulia_Skullette.png",
  "Ari Hauntington":"https://static.wikia.nocookie.net/monsterhigh/images/8/8f/Ari_Skullette.png",
  "Abbey Bominable":"https://static.wikia.nocookie.net/monsterhigh/images/4/44/Abbey_Skullette.png",
  "Operetta":"https://static.wikia.nocookie.net/monsterhigh/images/f/f7/Operetta_Skullette.png",
  "Rochelle Goyle":"https://static.wikia.nocookie.net/monsterhigh/images/b/b1/Rochelle_Skullette.png",
  "Robecca Steam":"https://static.wikia.nocookie.net/monsterhigh/images/c/c1/Robecca_Skullette.png",
  "Venus McFlytrap":"https://static.wikia.nocookie.net/monsterhigh/images/d/d8/Venus_skullette.png",
  "Spectra Vondergeist":"https://static.wikia.nocookie.net/monsterhigh/images/b/be/Spectra%27s_Skullette.png",
  "Toralei Stripe":"https://static.wikia.nocookie.net/monsterhigh/images/7/7a/Toralei_Skullette.png",
  "Meowlody":"https://static.wikia.nocookie.net/monsterhigh/images/4/49/Meowlody_Skullette.png",
  "Purrsephone":"https://static.wikia.nocookie.net/monsterhigh/images/8/81/Purrsephone_Skullette.png",
  "Nefera de Nile":"https://static.wikia.nocookie.net/monsterhigh/images/1/17/Nefera_Skullette.png",
  "Deuce Gorgon":"https://static.wikia.nocookie.net/monsterhigh/images/5/5a/Deuce_Skullette.png",
  "Jackson Jekyll":"https://static.wikia.nocookie.net/monsterhigh/images/4/4d/Jackson_Skullette.png",
  "Holt Hyde":"https://static.wikia.nocookie.net/monsterhigh/images/9/95/Holt_Skullette.png",
  "Clawd Wolf":"https://static.wikia.nocookie.net/monsterhigh/images/7/78/Clawd%27s_Skullette.png",
  "Gillington Gil Webber":"https://static.wikia.nocookie.net/monsterhigh/images/1/11/Gil%27s_Skullette.png",
  "Heath Burns":"https://static.wikia.nocookie.net/monsterhigh/images/9/98/HeathBurns_Skullette.png",
  "Sloman Slo Mo Mortavitch":"https://static.wikia.nocookie.net/monsterhigh/images/1/1c/SloMo%27s_Skullette.png",
  "Invisi Billy":"https://static.wikia.nocookie.net/monsterhigh/images/4/44/Invisi%27s_Skullette.png",
  "Howleen Wolf":"https://static.wikia.nocookie.net/monsterhigh/images/d/d3/Howleen_Skullette.png",
  "Gigi Grant":"https://static.wikia.nocookie.net/monsterhigh/images/a/ac/Gigi%27s_Skullette.png",
  "Twyla Boogeyman":"https://static.wikia.nocookie.net/monsterhigh/images/1/15/Twyla%27s_skullette.jpg",
  "Catty Noir":"https://static.wikia.nocookie.net/monsterhigh/images/f/f4/CattyNoir_Skullette.png",
  "Skelita Calaveras":"https://static.wikia.nocookie.net/monsterhigh/images/1/1a/Skelita_Skullette.png",
  "Jinafire Long":"https://static.wikia.nocookie.net/monsterhigh/images/2/2a/Skullette_-_Jinafire_Long.png",
  "Catrine DeMew":"https://static.wikia.nocookie.net/monsterhigh/images/8/8f/Catrine_skullette.jpg",
  "Garrott du Roque":"https://static.wikia.nocookie.net/monsterhigh/images/1/1c/Garrot_Skullette.png",
  "Scarah Screams":"https://static.wikia.nocookie.net/monsterhigh/images/8/88/Scarah_Skullette.png",
  "Hoodude Voodoo":"https://static.wikia.nocookie.net/monsterhigh/images/4/42/Hoodude_Skullette.png",
  "Iris Clops":"https://static.wikia.nocookie.net/monsterhigh/images/5/5c/Iris.png",
  "Manny Taur":"https://static.wikia.nocookie.net/monsterhigh/images/d/d6/Manny_Skullette.png",
  "Headless Headmistress Bloodgood":"https://static.wikia.nocookie.net/monsterhigh/images/f/fc/Bloodgood_Skullette.png",
  "Wydowna Spider":"https://static.wikia.nocookie.net/monsterhigh/images/e/ea/Wydowna%27s_Skullette.png",
  "Jane Boolittle":"https://static.wikia.nocookie.net/monsterhigh/images/e/e3/Jane%27s_Skullette.jpg",
  "Gilda Goldstag":"https://static.wikia.nocookie.net/monsterhigh/images/b/b1/Gilda_Skullette.png",
  "Honey Swamp":"https://static.wikia.nocookie.net/monsterhigh/images/4/40/Honey_Skullette.png",
  "Clawdia Wolf":"https://static.wikia.nocookie.net/monsterhigh/images/d/d9/Clawdia_SKullette.png",
  "Elissabat":"https://static.wikia.nocookie.net/monsterhigh/images/a/a2/Elissabat%27s_Skullette_2.png",
  "Viperine Gorgon":"https://static.wikia.nocookie.net/monsterhigh/images/a/a2/Viperine%27s_Skullette.png",
  "Avea Trotter":"https://static.wikia.nocookie.net/monsterhigh/images/7/78/Avea%27s_Skullette.PNG",
  "Bonita Femur":"https://static.wikia.nocookie.net/monsterhigh/images/2/25/Bonita_Skullette.png",
  "Neighthan Rot":"https://static.wikia.nocookie.net/monsterhigh/images/5/5f/Neighthans_Skullette.png",
  "Sirena Von Boo":"https://static.wikia.nocookie.net/monsterhigh/images/b/b8/Sirena%27s_skullette.jpg",
  "River Styxx":"https://static.wikia.nocookie.net/monsterhigh/images/2/23/River%27s_Skullette.PNG",
  "Kiyomi Haunterly":"https://static.wikia.nocookie.net/monsterhigh/images/c/cd/Kiyomi%27s_Skullette.png",
  "Porter Geiss":"https://static.wikia.nocookie.net/monsterhigh/images/b/bc/Porter%27s_Skullette.png",
  "Vandala Doubloons":"https://static.wikia.nocookie.net/monsterhigh/images/e/ea/Vandala%27s_Skullette.PNG",
  "Astranova":"https://static.wikia.nocookie.net/monsterhigh/images/a/a7/Astranova_Skullette.png",
  "Luna Mothews":"https://static.wikia.nocookie.net/monsterhigh/images/8/88/Luna_Skullette.png",
  "Elle Eedee":"https://static.wikia.nocookie.net/monsterhigh/images/e/ec/Elle_Skullette.png",
  "Mouscedes King":"https://static.wikia.nocookie.net/monsterhigh/images/b/b0/Mouscedes%27s_Skullette.PNG",
  "Finnegan Wake":"https://static.wikia.nocookie.net/monsterhigh/images/1/13/Finnegan_Skullette.PNG",
  "Amanita Nightshade":"https://static.wikia.nocookie.net/monsterhigh/images/e/e1/Amanita%27s_Skullette.PNG",
  "Gooliope Jellington":"https://static.wikia.nocookie.net/monsterhigh/images/6/62/Gooliope%27s_Skullette.png",
  "Marisol Coxi":"https://static.wikia.nocookie.net/monsterhigh/images/6/68/Marisol%27s_Skullette.png",
  "Lorna McNessie":"https://static.wikia.nocookie.net/monsterhigh/images/3/32/Lorna_Skullette.png",
  "Batsy Claro":"https://static.wikia.nocookie.net/monsterhigh/images/b/b7/Batsy%27s_Skullette.jpg",
  "Kjersti Trollson":"https://static.wikia.nocookie.net/monsterhigh/images/4/4d/Kjersti_SKullette.png",
  "Isi Dawndancer":"https://static.wikia.nocookie.net/monsterhigh/images/1/14/Isi%27s_Skullette.PNG",
  "C.A. Cupid":"https://static.wikia.nocookie.net/monsterhigh/images/9/92/C.A._Cupid_Skullette.png",
  "Kieran Valentine":"https://static.wikia.nocookie.net/monsterhigh/images/9/92/Kieran_Skullette.png",
  "Djinni Whisp Grant":"https://static.wikia.nocookie.net/monsterhigh/images/7/7e/Whisp_Skullette.PNG",
  "Casta Fierce":"https://static.wikia.nocookie.net/monsterhigh/images/3/34/CastaFierce_Skullette.png",
  "Peri & Pearl Serpentine": "https://4.bp.blogspot.com/-csinxq1cdDY/V_GroDA9WCI/AAAAAAAAPeM/wOGgWU39j0EkhbTFPAeqKyjrourfc8yhQCLcB/s400/Peri%2B%2526%2BPearl%2BSerpentine%2B-%2BSkullette.png",
  "Kala Mer'ri": "https://1.bp.blogspot.com/-PSW9F8kdKHk/V_GrmvtSyVI/AAAAAAAAPdY/B_71B0RcAu0zzsKu5zPSsDZywwLrLIE2gCLcB/s400/Kala%2BMer%2527ri-%2BSkullette.png"
};

// export const icons:string[] = ["https://static.wikia.nocookie.net/monsterhigh/images/4/44/Abbey_Skullette.png", "https://static.wikia.nocookie.net/monsterhigh/images/3/34/CastaFierce_Skullette.png"]

export const iconsLogo = {
  "Signature":"https://static.wikia.nocookie.net/monsterhigh/images/7/75/Logo_-_Monster_High.jpg",
  "Dawn of the Dance":"https://static.wikia.nocookie.net/monsterhigh/images/3/3e/Assortment_logo_-_Dawn_of_the_Dance.jpg",
  "Gloom Beach":"https://static.wikia.nocookie.net/monsterhigh/images/7/79/Gloom_Beach_Icon.jpg",
  "Sweet 1600":"https://static.wikia.nocookie.net/monsterhigh/images/9/9f/Sweet_1600_Icon.jpg",
  "Dead Tired":"https://static.wikia.nocookie.net/monsterhigh/images/2/2b/Dead_Tired_Icon.jpg",
  "Skull Shores":"https://static.wikia.nocookie.net/monsterhigh/images/4/45/SkullShoresLogo.png",
  "Dot Dead Gorgeous":"https://static.wikia.nocookie.net/monsterhigh/images/e/e2/Assortment_logo_-_Dot_Dead_Gorgeous.png",
  "Ghouls Rule":"https://static.wikia.nocookie.net/monsterhigh/images/1/16/Assortment_logo_-_Ghouls_Rule.png",
  "I Love Fashion":"https://static.wikia.nocookie.net/monsterhigh/images/7/73/I_Heart_Fashion_Icon.png",
  "Scaris: City of Frights":"https://static.wikia.nocookie.net/monsterhigh/images/3/3e/Assortment_logo_-_Scaris_City_of_Frights.jpg",
  "Ghoul’s Alive!":"https://static.wikia.nocookie.net/monsterhigh/images/7/7e/Assortment_logo_-_Ghoul%27s_Alive.png",
  "Skultimate Roller Maze":"https://static.wikia.nocookie.net/monsterhigh/images/a/ae/Assortment_logo_-_Skultimate_Roller_Maze.png",
  "Dance Class":"https://static.wikia.nocookie.net/monsterhigh/images/6/63/Assortment_logo_-_Dance_Class.jpg",
  "Picture Day":"https://static.wikia.nocookie.net/monsterhigh/images/e/e5/Assortment_logo_-_Picture_Day.png",
  "Power Ghouls":"https://static.wikia.nocookie.net/monsterhigh/images/f/f3/Assortment_logo_-_Power_Ghouls.png",
  "13 Wishes":"https://static.wikia.nocookie.net/monsterhigh/images/8/8f/Assortment_logo_-_13_Wishes.jpg",
  "Ghoul’s Night Out":"https://static.wikia.nocookie.net/monsterhigh/images/0/04/Assortment_logo_-_Ghouls_Night_Out.png",
  "Art Class":"https://static.wikia.nocookie.net/monsterhigh/images/8/87/Assortment_logo_-_Art_Class.png",
  "Music Festival":"https://static.wikia.nocookie.net/monsterhigh/images/b/b2/Assortment_logo_-_Music_Festival.png",
  "Monster Exchange":"https://static.wikia.nocookie.net/monsterhigh/images/a/a1/Monster_Exchange_Icon.png",
  "Zombie Shake":"https://static.wikia.nocookie.net/monsterhigh/images/a/af/Zombie_Shake_Icon.png",
  "Freaky Fusion":"https://static.wikia.nocookie.net/monsterhigh/images/6/61/Freaky_Fusion_Icon.png",
  "Haunted":"https://static.wikia.nocookie.net/monsterhigh/images/3/34/Haunted_Icon.png",
  "Gloom and Bloom":"https://static.wikia.nocookie.net/monsterhigh/images/e/e2/Gloom_and_Bloom_Icon.png",
  "Coffin Bean":"https://static.wikia.nocookie.net/monsterhigh/images/1/1c/Coffin_Bean_Icon.png",
  "Creepateria":"https://static.wikia.nocookie.net/monsterhigh/images/d/d4/Creepateria_Icon.png",
  "Freaky Field Trip":"https://static.wikia.nocookie.net/monsterhigh/images/1/10/Freaky_Field_Trip_Icon.png",
  "Geek Shriek":"https://static.wikia.nocookie.net/monsterhigh/images/7/7b/Geek_Shriek_Icon.png",
  "Boo York, Boo York":"https://static.wikia.nocookie.net/monsterhigh/images/5/52/Boo_York%2C_Boo_York_Icon.png",
  "Freak du Chic":"https://static.wikia.nocookie.net/monsterhigh/images/5/58/Freak_Du_Chic_Noir_Icon.png",
  "Great Scarrier Reef":"https://static.wikia.nocookie.net/monsterhigh/images/4/4e/Yayomg-great-scarrier-reef-333x166_%282%29.png",
  "Scarnival":"https://static.wikia.nocookie.net/monsterhigh/images/b/b6/Clawd_wolf_scarnival_booth_doll_in_box.png",
  "Gore-geous Accessories":"https://static.wikia.nocookie.net/monsterhigh/images/c/c3/Gore-geous_Accessories_Icon.png",
  "Fangtastic Fitnes":"https://static.wikia.nocookie.net/monsterhigh/images/a/a8/Fangtastic_Fitness_Icon.png",
  "Ghoul Fair":"https://static.wikia.nocookie.net/monsterhigh/images/4/40/Ghoul_Fair_Icon.png",
  "Frightfully Tall Ghouls":"https://static.wikia.nocookie.net/monsterhigh/images/3/3b/Frightfully_Tall_Ghouls_Icon.png",
  "Skullector":"https://static.wikia.nocookie.net/monsterhigh/images/7/79/Skullector.png"
}


